### ISSUE TITLE
weird feature rendering base on zoom

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#176]
I have an issue with feature rendering. The video shows it on iOS but i have the same problem on ios.
I don't understand why some peaks are appearing and disappearing. It does not seem to be related to the vector tile containing the peak or not as it happing during "float" zoom between for example 13 and 14

I use ```carto.streets,contours```
Here is the mss related to peaks.
```
#mountain_peak {

      shield-name: @name + '\n'  + [ele] + 'm';
      shield-face-name: @mont;
      shield-size: 11;
      shield-file: @peak_shield;
      shield-unlock-image: true;
      shield-fill: @peak_label;
      shield-halo-fill: @peak_halo;
      shield-halo-radius: 1;
      shield-halo-rasterizer: fast;
      shield-placement: [nuti::texts3d];
      shield-text-dy: 10;
      shield-text-dx: 0;
      shield-line-spacing: -2;
}
```

I can send an example if necessary. It actually a nativescript module example.

![jan-24-2018 19-43-43](https://user-images.githubusercontent.com/655344/35350658-e8e21b18-013e-11e8-9a71-cf97ed7d54b5.gif)

**Comment by mtehver** [comment]
Interesting. Looks like the id-s of the POIs are changing depending on the zoom level. @jaakla - we had a similar issue with city labels and it was fixed with the latest OMT schema. Is the latest OMT version live or still in staging?

**Comment by jaakla** [comment]
The OMT schema improvement (https://github.com/openmaptiles/openmaptiles/issues/303) is deployed right now and should be in use by next week.

**Comment by mtehver** [comment]
@farfromrefug The latest version of the tiles is now live. Can you test and check if the issue is now fixed? Thanks.

**Comment by farfromrefug** [comment]
@mtehver I tried with the rc2 and it's definitely better ! Thanks a lot

**Comment by farfromrefug** [comment]
Actually i still see the issue on Android. This is really weird because on ios with rc2 i dont see the issue. But on android i do. I use the same source ```carto.streets```, i cleared the cache (even removed the app), and i still see the issue.
Is it not only related to the online source and not the sdk itself?

**Comment by mtehver** [comment]
Strange, as this is an issue with the tiles (missing ids), not SDK. RC2 itself does not contain any changes related to this. BTW, are you using online tiles? I believe we have only fixed this for online tiles. Our offline packages are not yet updated.

**Comment by farfromrefug** [comment]
@mtehver any news on this one?

**Comment by mtehver** [comment]
Closing this, SDK 4.2.0 has 'feature-id' CartoCSS properties to fix the issue.

**Comment by farfromrefug** [comment]
@mtehver i would like to reopen that issue.
I am still seeing this with shields (so no feature-id) need on the 4.3.0.RC1
![Apr-13-2020 22-04-39](https://user-images.githubusercontent.com/655344/79156332-f7aaee00-7dd2-11ea-8a13-01e04675943b.gif)
The gif is not of great quality(could not do better on github) but if you look at the center You will see that depending on zoom in/out we dont get the same feature to render.
Here is the corresponding rule: 
```
#mountain_peak {
	shield-name: @name ?  ( [ele] ? [ele] + 'm' + '\n ' + @name : @name): '';
	shield-face-name: @mont_md;
	// shield-size: 9;
	shield-size: linear([view::zoom], (7, 6), (13, 8), (18, 12))- 0.000001 * [rank]; 
	shield-line-spacing: 10;
	shield-file: url(symbols/[class].svg);
	shield-fill: @peak_label;
}
```
It is a very simple rule and i use the rank + font size to give "order" as you explained.
It should always follow the same rule .
And in this case it should always show Mont Blanc because it has a rank of 1

**Comment by farfromrefug** [comment]
I want to add something more on this .
I just saw something weird on line labels.
If you look at the gif. When zooming slowly (beginning) the label disappear pretty fast
But if i do it fast i can see that it can actually draw on the line when zoomed out.
I have no min distance nor spacing set on the text
![Apr-14-2020 12-18-20](https://user-images.githubusercontent.com/655344/79213797-113b4c80-7e4a-11ea-9032-9e7544babf29.gif)
