### ISSUE TITLE
Map Layers click events

### ISSUE THREAD

**Issue by slobglob** [CartoDB/mobile-sdk#280]
Hey,
I'm using this SDK and providing multiple layers to the map (3 map layers and about 4 data layers of different types of vector elements).
One of those layers is a clustered layer, sometimes while having clusters on the map, clicking on them triggers the `onClick` event of the vector element layer which is behind it.
Let's say I have X layer which is in index 3, and a clustered layer Y which is in index 5, from what I understood from the docs - the layer with the higher index has the priority (also in visibility and for click events). 

I'm using the latest 4.1.6 version, using java, happens on all phones I've been testing from multiple API levels.

Any idea how to make the cluster first always (in visibility and clicks)?

**Comment by mtehver** [comment]
Hi,

just to be clear - you have overlapping elements (clusters and on the layer behind it) and then your receive clicks on the layer below clustering layer? Do you have `VectorElementEventListenter` instances on both layers? If you do not have it on clustering layer, an instance that simply returns true in `onVectorElementClicked` may fix the issue.

**Comment by slobglob** [comment]
Yes,
it is exactly how you described it.
Actually I have a `VectorElementEventListener` on both of the layers, it's the same listener on both of them.
And I do return `true` once the click is handled.

Sounds like it should work but it still doesn't.

**Comment by mtehver** [comment]
I have reproduced this. This is actually quite tricky to fix to the complicated rendering order used by the SDK. We plan to have a fix for this in 4.2.0RC2, which we hope to release sometime next week.

Thanks for reporting!

**Comment by slobglob** [comment]
@mtehver 
Great to hear! Waiting for that fix!

**Comment by mtehver** [comment]
@slobglob SDK4.2.0RC2 is now out and should fix the issue.

**Comment by slobglob** [comment]
@mtehver 
Is there any expectation when the final 4.2.0 should be out?

**Comment by mtehver** [comment]
@slobglob We expect to release it in the end of May. RC2 should be really close to the final version, there are currently no pending fixes or features.

**Comment by slobglob** [comment]
@mtehver 
Great! I'll give this a try and will update.

**Comment by mtehver** [comment]
Closing this as SDK 4.2.0 is now out and should fix this. If there are remaining issues, this can be re-opened.

**Comment by slobglob** [comment]
Couldn't test this version... When I upgrade to 4.2.0 my app completely gets stuck, freezes and eventually dies. Still not sure why this is happening, went through the change-log and I didn't find any braking issues.
Kind of hard for me to debug as it gets stuck as soon as the map gets loaded :|.
Any idea?

**Comment by mtehver** [comment]
@slobglob No idea, did this happen with RC1/2 also? In order to track this, we would need a small test case demonstrating this.

**Comment by slobglob** [comment]
@mtehver 
Yes it does. Completely freezes sometimes I need to reboot the device itself while in debug

**Comment by mtehver** [comment]
@slobglob In order to investigate this, I would need one of the following (in the order of preference):

1) Minimal test app demonstrating the issue
2) Full app source code
3) App APK

Any chance you could provide us one of these?

**Comment by slobglob** [comment]
Yes, I'll post a video of the issue soon.
Full source code can be tricky, after you'll review the video I'll see how can we go from there.
Thanks

**Comment by mtehver** [comment]
@slobglob Hi, a follow-up on the issue. Did you manage to fix this or is there anything we can do on our side?

**Comment by slobglob** [comment]
Didn't had the chance to debug this thoroughly yet, it is reproduce-able 100% of times. But I won't have the option to send you the source code (for obvious reasons).
I'll update you once I get back to this issue again. Thanks for the follow-up.

**Comment by mtehver** [comment]
@slobglob We are getting close to releasing CARTO Mobile SDK 4.2.1RC1, so we are trying to solve and close reported issues. Any chance you could give us more information so we could try to reproduce this 4.2.0 regression ourselves? Thanks.

**Comment by slobglob** [comment]
@mtehver Hey, didn't had the time to go back to this and break it down to pieces.
Right now I'm still running 4.1.6, if you want you can close this one for now and I'll re open it when I'll have more relevant information.

**Comment by mtehver** [comment]
@slobglob Thanks! I will close this issue. Once you have more details, I think it would be best to open a new issue as it is likely not related to the original click event ordering.
